### ISSUE TITLE
show history plots incl. mean values

### ISSUE THREAD

**Issue by silberzwiebel** [CodeforKarlsruhe/opensense#12]
Something similar to the graph tab of [the opensensemap-widget](https://sensebox.github.io/opensensemap-widget/iframe.html?senseboxId=59c67b5ed67eb50011666dbb) to give an impression of the history of sensor values.

I think it would also be interesting to additionally plot the mean sensor value of the last 24 hours / weeks / years (configurable). Possibly even the mean value of nearby senseboxes?

Generally speaking, I would be interested in contributing an implementation of this idea to your project (I was thinking about android widgets before someone pointed me to your project). However, I'm not sure how much time I can spend on this in the near future.

**Comment by dbaelz** [comment]
That's a great idea and it would be great if you provide such a widget.

Besides that I plan to add an app part with more features and screens to Open Sense. Certainly, there will be screens in the app to show history and statistics. I added your idea  to the issue #13. Unfortunately, I won't have the time to develop this app part in the coming weeks. So if you start with the widget part, I'm be glad to review and integrate it as soon as possible.
